#
# Basic settings.
#
# url: http://localhost:4000
# baseurl: ""
url: https://denkstaette.github.io
baseurl: ""
title: DENK.STÄTTE
description: Mensch und Boden sind keine Wirtschaftsgüter, weder im Ganzen noch in Teilen.
avatar: /assets/img/dove.png
favicon: /assets/img/dove.png
# language: ja
language: de

#
# Icons
#
icons:
  rss: true
  email:
  github: denkstaette
  bitbucket:
  twitter: 
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
# google_analytics: # e.g. UA-000000-01
# disqus:

#
# Localizations.
#
str_next: Ältere Beiträge
str_prev: Neuere Beiträge
str_read_more: Weiter lesen...
str_search: Suche
str_recent_posts: Letzte Beiträge
str_show_all_posts: Alle Beiträge

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: false
  facebook: false # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url: //denkstaette.github.io/assets/img/ogp.png
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Plugins.
#
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
